import type { ArticleBlock, WritingItem } from "@/content/types";

type StoryPart =
  | { kind: "h2"; text: string }
  | { kind: "paragraph"; text: string }
  | { kind: "quote"; text: string };

function body(slug: string, parts: StoryPart[]): ArticleBlock[] {
  return parts.map((part, index) => ({
    _type: "block",
    _key: `${slug}-${index}`,
    style: part.kind === "paragraph" ? "normal" : part.kind === "quote" ? "blockquote" : "h2",
    children: [{
      _type: "span",
      _key: `${slug}-${index}-text`,
      text: part.text,
      marks: [],
    }],
    markDefs: [],
  }));
}

const projectArticleDrafts: WritingItem[] = [
  {
    id: "making-ai-app-videos-without-the-slop",
    title: "Trying to make AI app videos without the AI slop",
    description: "An experiment in using generative video to explain the apps I build without producing the glossy, generic content people have learnt to ignore.",
    date: "19 July 2026",
    articleType: "project-story",
    projectName: "Marketing Engine",
    projectId: "marketing-engine",
    body: body("social-marketing", [
      { kind: "paragraph", text: "Building an app and explaining why it exists are two different jobs. I enjoy the first one far more. Once LightScout and Rest+Rise became real products, though, I could not keep treating the second as something I would eventually get around to." },
      { kind: "paragraph", text: "This project is my attempt to find a repeatable way to make short videos about the apps. The obvious attraction is generative AI: it can turn an idea into footage quickly and remove much of the production overhead. The obvious problem is that it can also produce exactly the kind of glossy, synthetic filler that now gets labelled AI slop." },
      { kind: "h2", text: "The constraint is truth" },
      { kind: "paragraph", text: "A marketing video still needs to say something specific. If the same clip could advertise a meditation app, a bank and a protein powder, it is not helping anyone understand the product. The experiment is therefore less about generating more footage and more about finding a process that keeps the product idea intact." },
      { kind: "paragraph", text: "For LightScout, that means showing the moment a traveller actually has the problem: arriving somewhere unfamiliar, looking for a composition and trying to work out where the light will fall. It does not mean asking a video model to recreate the app interface. The result would be inaccurate, would age immediately and would make a real product look fake. The app belongs in the narration, captions and final call to action; the visual story should stay grounded in what the photographer is doing." },
      { kind: "paragraph", text: "Rest+Rise needs a different visual language. It is about the transition into and out of a day: putting the phone down, preparing a room, moving, breathing or writing. Again, the useful material is the recognisable human behaviour, not a perfect-looking person performing a vague wellness montage." },
      { kind: "h2", text: "A small content system, not a content machine" },
      { kind: "paragraph", text: "I am experimenting with a workflow that separates the durable parts from the disposable ones. The durable parts are the audience, the product truth, the opening idea and the reason to care. The disposable parts are individual scenes, cuts, captions and formats. Those can be regenerated and tested without changing what the video is actually trying to say." },
      { kind: "paragraph", text: "That distinction matters because automation creates a temptation to optimise for volume. I am not trying to fill a calendar with interchangeable posts. I would rather make fewer pieces that demonstrate a real use case, have a point of view and look as though someone made a choice." },
      { kind: "quote", text: "The test is simple: if I removed the app name, would the idea still clearly belong to this product?" },
      { kind: "h2", text: "What I am learning" },
      { kind: "paragraph", text: "AI is already useful for exploring directions, creating shots that would be impractical for a one-person project and rapidly making variants. It is much less useful at deciding what is worth saying. Without a clear brief it averages everything out, both visually and verbally." },
      { kind: "paragraph", text: "The work is still experimental. There is no grand growth result to report and the project folder is deliberately not pretending to be a finished platform. What I am building is a better judgement loop: start from a real product problem, generate only what supports it, edit aggressively and keep the parts that feel specific." },
      { kind: "paragraph", text: "If it works, the outcome will not be an autonomous marketing engine. It will be a practical way for me to show the products I am already building without the marketing becoming another full-time project — and without adding more synthetic noise to everyone else's feed." },
    ]),
  },
  {
    id: "from-google-doc-to-rest-rise",
    title: "From a morning-routine Google Doc to Rest+Rise",
    description: "How a personal routine tracker became a science-backed mobile app — and what shipping it on iOS and Android taught me about cross-platform development.",
    date: "19 July 2026",
    articleType: "project-story",
    projectName: "Rest+Rise",
    projectId: "rest-rise",
    body: body("rest-rise", [
      { kind: "paragraph", text: "Rest+Rise started in a Google Doc. I was trying to be more deliberate about my mornings, so I tracked the routines I was attempting, what seemed useful and what I wanted to try next. It worked, but it also exposed the limitations of a document: it could record a routine, but it could not help me build one, run it or understand whether I was actually sticking to it." },
      { kind: "paragraph", text: "At the same time, I kept finding new ideas about sleep, light, movement, focus and recovery. Some had reasonable evidence behind them; others were confident wellness claims repeated until they sounded like facts. I wanted one place that made the distinction visible and turned the useful ideas into something a normal person could fit into the first or last part of a day." },
      { kind: "h2", text: "Turning research into an actual routine" },
      { kind: "paragraph", text: "The product is organised around two moments: Rise, the first 60 minutes of the morning, and Rest, the last 60 minutes of the evening. It contains a library of time-bounded rituals, evidence labels and source material. People can browse the options, assemble their own stack, reorder it and then run it as a checklist or timer." },
      { kind: "paragraph", text: "The most important product decision was to avoid making the app another guilt machine. Morning-routine content often implies that a good day requires a heroic sequence before breakfast. Rest+Rise is built around the time someone actually has. A short routine that gets used is more valuable than an ideal one that collapses after three days." },
      { kind: "paragraph", text: "That also changed how the research is presented. Evidence is not decoration and the app should not claim certainty where there is none. The job is to give someone enough context to make a sensible choice, then get out of the way while they do it." },
      { kind: "h2", text: "The cross-platform experiment" },
      { kind: "paragraph", text: "My first app, LightScout, was native SwiftUI. With Rest+Rise I deliberately chose React Native and Expo. Partly I wanted the app on both iOS and Android; partly I wanted to understand the trade-offs for myself rather than repeating the usual arguments about cross-platform development." },
      { kind: "paragraph", text: "The shared codebase did what it promised. I could build the core experience once and take it to both stores. It did not make the platforms identical. Authentication, subscriptions, store configuration, release processes and the last layer of interface behaviour still have platform-specific edges. Shared code reduces one category of work; it does not remove the need to understand two products, two ecosystems and two sets of failure modes." },
      { kind: "quote", text: "I am glad I built a cross-platform app. I am also much less likely to choose cross-platform by default next time." },
      { kind: "paragraph", text: "That is not a verdict that React Native or Expo are poor tools. They are capable, and Rest+Rise now exists on both platforms because of them. It is a judgement about the kind of solo work I enjoy and where I want to spend complexity. For a future personal app, I would probably prefer to make one platform feel excellent and only add another when the demand justifies it." },
      { kind: "h2", text: "What the app became" },
      { kind: "paragraph", text: "The current product goes well beyond the original document. It supports custom routines, generated quick stacks, guided sessions, history and a paid Insights layer that can turn usage into a weekly coaching note. The underlying idea, however, is unchanged: make the useful research easier to act on in the two parts of the day where small choices compound." },
      { kind: "paragraph", text: "I still think of the Google Doc as the right first version. It proved I cared about the problem before I spent months turning it into software. The app was not the starting insight; it was what became possible once the manual system had shown me exactly where it broke down." },
    ]),
  },
  {
    id: "can-ai-ship-a-fun-ios-game",
    title: "Can an AI model research, build and ship a fun iPhone game?",
    description: "Why I built a benchmark around the whole product journey — not another isolated coding task — and what the first runs are revealing.",
    date: "19 July 2026",
    articleType: "project-story",
    projectName: "Ship a Game",
    projectId: "gaming-benchmark",
    links: [
      { label: "Explore the live benchmark", href: "https://shipagame.weevolve.app/" },
      { label: "Read the Brinkball report", href: "https://shipagame.weevolve.app/games/brinkball" },
      { label: "Read the Ringbloom report", href: "https://shipagame.weevolve.app/games/ringbloom" },
    ],
    body: body("gaming-benchmark", [
      { kind: "paragraph", text: "Every new frontier model arrives with a fresh set of benchmark scores. Soon afterwards, YouTube fills with people asking it to build a web game. The results are often impressive for a few minutes, but they leave out most of the difficult questions. Did the model research what makes the genre work? Is the game still interesting after the novelty wears off? Can it handle assets, testing, store requirements and the long tail of getting a real product ready to submit?" },
      { kind: "paragraph", text: "I wanted to test the whole journey. Ship a Game gives a model one challenge: research, design, build and prepare a paid iOS game for App Store Connect. The human only handles the account actions Apple requires from the account holder and the final submission tap." },
      { kind: "h2", text: "The intervention log is the score" },
      { kind: "paragraph", text: "A coding benchmark can hide a surprising amount of help. Someone fixes the environment, clarifies the prompt, chooses the engine or rescues a broken build, and the final screenshot still looks like a one-shot success. In this benchmark every intervention is part of the result." },
      { kind: "paragraph", text: "I record nudges, fixes and rescues. A model that makes a good game after several targeted corrections has demonstrated something useful, but it has not demonstrated full autonomy. The log makes that distinction legible. It also makes failure interesting: the point is to see where the current boundary really is, not to manufacture a win for a preferred model." },
      { kind: "paragraph", text: "Each model runs in its own first-party coding environment on the same provisioned Mac, with the same broad capability surface and the same challenge. It can choose its engine and its approach. The benchmark therefore tests research, planning, taste, tool use, debugging and delivery together." },
      { kind: "h2", text: "The surprising answer so far" },
      { kind: "paragraph", text: "The models can build the games. Ringbloom, built through Codex, and Brinkball, started in Claude Code, are both live on the App Store. Brinkball reached its first submission with two nudges and no fixes or rescues; its later improvement round also exposed an important model-fallback complication that the full report documents. That is a much stronger—and messier—result than generating a playable web prototype in a browser tab." },
      { kind: "paragraph", text: "The more interesting question is whether the world finds the games fun. I do, but I am both the person running the experiment and someone unusually interested in the process. Store approval, purchases, play time and retention are harder tests than my own enthusiasm. Those results need to remain separate from the autonomy score: a model can ship efficiently and still make a mediocre game, or need help while making something people love." },
      { kind: "quote", text: "Shipping is one result. Making something strangers choose to keep playing is another." },
      { kind: "h2", text: "Why do the models keep making puzzle games?" },
      { kind: "paragraph", text: "There is already a pattern worth pushing on. Turn-based and puzzle-like designs are a rational choice for an autonomous model: the rules are bounded, the state is testable and the game does not depend on frame-perfect feel. That makes them excellent evidence of software delivery and a possible escape hatch from harder kinds of game design." },
      { kind: "paragraph", text: "A benchmark should not punish a model for making a sensible decision, but it should eventually test whether that decision has become a rut. Future prompts may need to constrain the genre or explicitly reward forms of play that rely on motion, timing or a less easily simulated kind of fun." },
      { kind: "h2", text: "What I am really measuring" },
      { kind: "paragraph", text: "This started as curiosity about model capability. It has become a compact test of end-to-end product work. Writing code is only one part. The model has to decide what to make, recognise weak output, recover from tools that do not behave as expected and finish a process full of unglamorous details." },
      { kind: "paragraph", text: "The first runs suggest the frontier has moved well beyond toy prototypes. They do not prove that an AI can independently make a successful game. That gap — between technically shipped and genuinely wanted — is exactly why I want to keep running the experiment." },
    ]),
  },
  {
    id: "somewhere-day-trip-planner",
    title: "Building the day-trip planner I actually wanted to use",
    description: "Somewhere began as a Replit hackathon project, but the problem survived the event: finding a genuinely good day out without doing an evening of research first.",
    date: "19 July 2026",
    articleType: "project-story",
    projectName: "Somewhere",
    body: body("somewhere", [
      { kind: "paragraph", text: "Somewhere began with a Replit hackathon, which was a useful forcing function: choose a problem, make the idea concrete and get something working. The event ended, but the product stayed interesting because it solves a problem I still have myself." },
      { kind: "paragraph", text: "Planning a day out sounds simple until the constraints appear. Where can I reach in the time available? Is the journey realistic by train or car? Does the destination contain enough things I care about? Can those places form a sensible route rather than a list of pins scattered across a map? Most discovery products answer one of those questions and leave the rest as homework." },
      { kind: "h2", text: "From inspiration to an itinerary" },
      { kind: "paragraph", text: "The core idea is to turn a few preferences into a day that could actually be followed. Somewhere takes a starting location, travel-time limit, transport choice and interests. It can suggest destinations, check them against real journey times, then build an itinerary from places of interest, lunch and the routes between each stop." },
      { kind: "paragraph", text: "That two-stage flow was an important correction. Asking an AI to produce a complete trip in one response is easy to demo and difficult to trust. Separating destination discovery from itinerary generation lets the system validate the big decision first. Once someone chooses where they are going, the search can become local and specific." },
      { kind: "paragraph", text: "The itinerary itself combines different kinds of work. Open map data provides candidate places. AI helps curate a coherent set rather than blindly returning the most popular results. Routing services check whether the order makes sense on foot or by public transport. The product value sits in that orchestration, not in pretending one model already knows every opening time and travel connection." },
      { kind: "h2", text: "The unglamorous product work" },
      { kind: "paragraph", text: "A hackathon rewards the visible path. A product has to survive repeated use, unreliable services and a bill. Some of the most important work after the first version was therefore defensive: rate limits, caching the expensive parts of the generation pipeline, monitoring failures and putting boundaries around free usage." },
      { kind: "paragraph", text: "That work does not make for the best demo, but it changes whether I would feel comfortable letting other people use the app. A generated trip is only useful if the system can explain failure, avoid wasting paid requests and return enough consistent information for someone to trust a day of their time to it." },
      { kind: "quote", text: "The product is not the itinerary text. It is the confidence that the day holds together." },
      { kind: "h2", text: "Why it is unfinished" },
      { kind: "paragraph", text: "Somewhere is not one of the projects I want to describe as done. The app has a substantial working foundation, but the positioning, discovery experience and operational shape still need attention. It also needs the simple test I care about most: would I repeatedly choose one of its plans over doing the research myself?" },
      { kind: "paragraph", text: "That is why it remains active rather than moving into an archive. Unlike an idea that was only entertaining during a hackathon, I can picture opening Somewhere on a free Saturday morning and asking it to get me out of the house. The next useful phase is not adding a longer feature list. It is returning to the core journey, using it for real trips and tightening every point where the generated plan loses credibility." },
      { kind: "paragraph", text: "The hackathon proved the concept could exist. The more interesting job is making it dependable enough that I stop thinking of it as a hackathon project at all." },
    ]),
  },
  {
    id: "warden-from-brainstorm-to-game",
    title: "What it took to turn Warden from a brainstorm into a game",
    description: "The design work, simulation and repeated rule changes behind a deterministic tactics game that finally became genuinely fun.",
    date: "19 July 2026",
    articleType: "project-story",
    projectName: "Warden",
    projectId: "warden",
    links: [{ label: "Warden support site", href: "https://tom-murton.github.io/warden/" }],
    body: body("warden", [
      { kind: "paragraph", text: "Before I made a benchmark that asks AI models to ship games, I tried to make one properly myself. Warden began as a relatively compact idea: a portrait tactics game, built around the satisfying clarity of moving a single piece on a small board." },
      { kind: "paragraph", text: "It became far more work than the brainstorm suggested. That is also what made it useful. A game can be technically complete, visually coherent and still have no reason for the player to make one move rather than another. Warden only became good when I stopped treating the first rules as the idea and started treating them as material to test." },
      { kind: "h2", text: "A small board with no excuses" },
      { kind: "paragraph", text: "Warden is a deterministic, zero-randomness tactics roguelite. You control one piece on a 6 × 6 dungeon board, descend through ten floors and eventually face the Bone Tyrant. Enemy intentions are visible. There is no lucky damage roll to rescue a poor choice and no hidden result to blame when a run ends." },
      { kind: "paragraph", text: "The portrait, one-thumb format forces the game to stay legible. Movement borrows the immediate literacy of chess, then upgrades mutate what the piece can do across a run. The aim is a sequence of compact decisions where the player can understand the danger, form a plan and feel responsible for the outcome." },
      { kind: "h2", text: "The kiting problem" },
      { kind: "paragraph", text: "The early versions had a structural flaw: survival was too often about keeping away from everything. If the strongest strategy is to circle the board while enemies shuffle behind you, the game may be solvable but it is not tense. Adding more enemy types would only disguise the problem." },
      { kind: "paragraph", text: "The solution was the Wards. Each floor contains soul-anchors that the enemies march towards. Lose them and the run ends. Suddenly distance has a cost. The player has to interpose, decide which threat matters and sometimes accept danger to protect the objective. The same board and movement rules began producing much better decisions because the player now had something to defend." },
      { kind: "quote", text: "The Wards did not add more game around the edges. They gave every move a reason." },
      { kind: "h2", text: "Using simulation without designing by spreadsheet" },
      { kind: "paragraph", text: "Because the rules are deterministic, Warden can be exercised headlessly across large numbers of boards and builds. The core suite now contains 176 tests. Simulations exposed forced-loss openings, dominant upgrades, difficulty cliffs and rules that sounded fair in prose but behaved differently in combination." },
      { kind: "paragraph", text: "That evidence made it possible to change the design aggressively without guessing about every consequence. It did not answer whether the game felt good in the hand. A bot can tell me that a floor is survivable; it cannot tell me whether spotting the move is satisfying, whether the threat language reads quickly on a phone or whether a ten-floor run has the right rhythm." },
      { kind: "paragraph", text: "The design loop therefore moved between rules, automated simulation and actual play. Some ideas survived. Others were cut even after they had been implemented because they reduced meaningful options or only looked like upgrades. The low-poly art is from a coherent licensed asset set rather than AI-generated imagery; the distinctiveness comes from the rules, composition and presentation rather than pretending generated assets have no provenance." },
      { kind: "h2", text: "Where it is now" },
      { kind: "paragraph", text: "Warden is launch-staged rather than publicly launched. A signed iOS build, store material and support site exist, but it still needs the remaining Apple account steps and a final real-device TestFlight check. That distinction matters: App Store preparation is not the same as having strangers play it." },
      { kind: "paragraph", text: "Even before that verdict, the project has answered the question that started it. The brainstorm could become a real game, but only after the original idea was challenged repeatedly. The fun did not arrive in the first prompt. It came from finding the strategy that flattened the experience, changing the stakes and doing the less glamorous work of proving the new rules held together." },
    ]),
  },
  {
    id: "building-lightscout-for-travellers",
    title: "Building the photography app I wanted while travelling",
    description: "LightScout began as a tool for serious photographers. Its better direction was simpler: help anyone arrive somewhere new and find a genuinely good place to take a photograph.",
    date: "19 July 2026",
    articleType: "project-story",
    projectName: "LightScout",
    projectId: "lightscout",
    links: [
      { label: "Visit LightScout", href: "https://www.lightscout.app" },
      { label: "Read the original build story", href: "https://www.linkedin.com/pulse/how-i-shipped-ios-app-store-without-writing-single-line-tom-murton-msm9e/" },
      { label: "View on the App Store", href: "https://apple.co/4c3huFE" },
    ],
    body: body("lightscout", [
      { kind: "paragraph", text: "LightScout was my first app and it is still the project I care about most. It sits directly between two things I love: travel and photography. The original frustration was familiar from almost every trip. I could arrive somewhere remarkable and still spend too much time cross-referencing maps, weather, sunset times and other people's photo guides before I knew where to go." },
      { kind: "paragraph", text: "I wanted the app I would open in that moment. Tell it where I am, what camera I have and how experienced I am; get a useful guide to where to stand, when the light is likely to work and what might be worth photographing." },
      { kind: "h2", text: "The first version aimed too narrowly" },
      { kind: "paragraph", text: "I initially thought about LightScout as a tool for serious photographers. That pushed the product towards technical depth: camera settings, weather detail, landscape features, sun information and increasingly elaborate analysis. Those things can be valuable, but the framing assumed the user already knew what kind of answer to ask for." },
      { kind: "paragraph", text: "The stronger need was much more ordinary. Most people travelling with an iPhone or camera are not trying to plan a professional shoot. They want to know what is worth seeing, where the interesting angle is and whether there is a better option than the same crowded viewpoint everyone else found on Instagram." },
      { kind: "paragraph", text: "That led to a broader and clearer product. Near Me can analyse the area around the user. Hidden Gems looks for less obvious locations. Other modes focus on views and nature, city scenes or architecture. The recommendations still adapt to equipment and experience, but the interface no longer expects someone to think like a professional before the app can help." },
      { kind: "quote", text: "The pivot was not from advanced photography to basic photography. It was from describing the technology to solving the moment." },
      { kind: "h2", text: "Building without writing the code myself" },
      { kind: "paragraph", text: "I have already written the detailed story of how the first version reached the App Store: roughly 100 hours over six months, an early vibe-coded prototype, a complete rebuild and a workflow where AI tools produced the Swift while I supplied the requirements, product decisions and review process." },
      { kind: "paragraph", text: "The most important lesson was not that an AI could generate a native iOS app. It was that the quality of the product work still determined whether the code went anywhere useful. The first prototype appeared quickly and became difficult to maintain. Clear phases, written specifications and reviews from multiple models made the rebuilt version shippable." },
      { kind: "paragraph", text: "The App Store added a different kind of education. Subscriptions, authentication, privacy material, screenshots, provisioning and review all had to work as a system. LightScout was rejected twice before approval, both times for fixable issues. Getting to the point where Apple could review it was harder than the individual corrections." },
      { kind: "h2", text: "The product keeps moving" },
      { kind: "paragraph", text: "Shipping did not freeze the original idea. LightScout now combines location scouting, weather, light, mapping and AI-generated guidance in a native iPhone app. The marketing site has also grown into a library of free destination guides, which serves the same underlying job even before someone downloads anything." },
      { kind: "paragraph", text: "The shift towards travellers has made prioritisation easier. A feature earns its place if it helps someone decide where to go, when to go or what to try when they arrive. Technical sophistication is useful only when it improves one of those decisions. More data is not automatically a better scout report." },
      { kind: "h2", text: "Why it remains my best project" },
      { kind: "paragraph", text: "LightScout is not my best project because it has the largest audience or because every part is finished. It is the best expression of how I like to work. It began with a problem I understood personally, forced me to learn an unfamiliar delivery process and kept changing as the product became clearer." },
      { kind: "paragraph", text: "It also changed my relationship with AI development. Before LightScout, I could discuss the tools and their likely impact. Afterwards, I had dealt with the architecture, migrations, reviews, broken integrations and store constraints that sit between a convincing demo and a real product. That practical understanding has carried into everything I have built since." },
      { kind: "paragraph", text: "The app is still the same promise I wanted on my own travels: spend less time researching the photograph and more time being in the place where it might happen." },
    ]),
  },
];

const projectArticleOrder = [
  "building-lightscout-for-travellers",
  "from-google-doc-to-rest-rise",
  "can-ai-ship-a-fun-ios-game",
  "warden-from-brainstorm-to-game",
  "somewhere-day-trip-planner",
  "making-ai-app-videos-without-the-slop",
];

export const projectArticles = projectArticleOrder.flatMap((id) => {
  const article = projectArticleDrafts.find((item) => item.id === id);
  return article ? [article] : [];
});
